#
# ZSH configuration file
#
# Author: Nicolas G. Querol <nicolas.gquerol@gmail.com>
#

# load stuff
autoload -U colors && colors
autoload -U compinit && compinit
autoload -U bashcompinit && bashcompinit
autoload -U select-word-style && select-word-style bash
autoload -U vcs_info && vcs_info

zmodload zsh/complist
zmodload zsh/terminfo

setopt \
    hist_ignore_all_dups \
    hist_ignore_space \
    hist_reduce_blanks \
    prompt_subst \
    nobeep \
    nocheckjobs \
    nohup \
    listpacked \
    listtypes \
    extendedglob \
    completeinword \
    alwaystoend \
    correct \
    autocd \

# Source seperate config files
for r in $HOME/.zsh/*.zsh; do
    source $r
done

eval `dircolors -b`

# Disable this bloody XOFF
stty ixany
stty ixoff -ixon
